# Generated by Django 3.2.4 on 2021-07-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('membership_type', models.CharField(choices=[('Enterprice', 'Enterprice'), ('Professional', 'Professional'), ('Free', 'Free')], default='Free', max_length=30)),
                ('price', models.IntegerField(default=15)),
            ],
        ),
        migrations.DeleteModel(
            name='UserMembership',
        ),
    ]
